name: /gpfs/u/home/DLTM/DLTMhssn/scratch/py39_cu113
channels:
  - pytorch
  - dglteam
  - huggingface
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_kmp_llvm
  - abseil-cpp=20211102.0=h27087fc_1
  - aiohttp=3.8.1=py39hb9d737c_1
  - aiosignal=1.3.1=pyhd8ed1ab_0
  - anyio=3.5.0=py39h06a4308_0
  - apache-beam=2.43.0=py39hb9d737c_0
  - argon2-cffi=21.3.0=pyhd3eb1b0_0
  - argon2-cffi-bindings=21.2.0=py39h7f8727e_0
  - arrow-cpp=8.0.0=py39h60b952e_0
  - asttokens=2.0.5=pyhd3eb1b0_0
  - async-timeout=4.0.2=pyhd8ed1ab_0
  - attrs=22.1.0=py39h06a4308_0
  - aws-c-common=0.4.57=he6710b0_1
  - aws-c-event-stream=0.1.6=h2531618_5
  - aws-checksums=0.1.9=he6710b0_0
  - aws-sdk-cpp=1.8.185=hce553d0_0
  - babel=2.9.1=pyhd3eb1b0_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - beautifulsoup4=4.11.1=py39h06a4308_0
  - blas=1.0=mkl
  - bleach=4.1.0=pyhd3eb1b0_0
  - boost-cpp=1.73.0=h7f8727e_12
  - bottleneck=1.3.5=py39h7deecbd_0
  - brotli=1.0.9=h166bdaf_7
  - brotli-bin=1.0.9=h166bdaf_7
  - brotlipy=0.7.0=py39h27cfd23_1003
  - bzip2=1.0.8=h7b6447c_0
  - c-ares=1.18.1=h7f98852_0
  - ca-certificates=2023.08.22=h06a4308_0
  - certifi=2023.7.22=pyhd8ed1ab_0
  - cffi=1.15.1=py39h74dc2b5_0
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - click=8.0.4=py39h06a4308_0
  - cloudpickle=2.2.0=pyhd8ed1ab_0
  - crcmod=1.7=py39hb9d737c_1009
  - cryptography=38.0.1=py39h9ce1e76_0
  - cudatoolkit=11.3.1=h2bc3f7f_2
  - cycler=0.11.0=pyhd3eb1b0_0
  - cython=0.29.32=py39h6a678d5_0
  - dataclasses=0.8=pyhc8e2a94_3
  - datasets=2.7.0=py_0
  - dbus=1.13.18=hb2f20db_0
  - debugpy=1.5.1=py39h295c915_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - dgl-cuda11.3=0.9.1post1=py39_0
  - dill=0.3.1.1=pyhd8ed1ab_2
  - docker-pycreds=0.4.0=py_0
  - docopt=0.6.2=py_1
  - entrypoints=0.4=py39h06a4308_0
  - executing=0.8.3=pyhd3eb1b0_0
  - expat=2.4.9=h6a678d5_0
  - fastavro=1.7.0=py39hb9d737c_0
  - fastbpe=0.1.0=py39h1a9c180_4
  - fasteners=0.17.3=pyhd8ed1ab_0
  - ffmpeg=4.3=hf484d3e_0
  - fftw=3.3.9=h27cfd23_1
  - filelock=3.8.0=pyhd8ed1ab_0
  - fontconfig=2.13.1=hef1e5e3_1
  - fonttools=4.25.0=pyhd3eb1b0_0
  - freetype=2.12.1=h4a9f257_0
  - frozenlist=1.2.0=py39h7f8727e_0
  - fsspec=2022.11.0=pyhd8ed1ab_0
  - gflags=2.2.2=he1b5a44_1004
  - giflib=5.2.1=h7b6447c_0
  - git-lfs=3.4.0=ha770c72_0
  - gitdb=4.0.7=pyhd3eb1b0_0
  - gitpython=3.1.29=pyhd8ed1ab_0
  - glib=2.69.1=h4ff587b_1
  - glog=0.6.0=h6f12383_0
  - gmp=6.2.1=h295c915_3
  - gnutls=3.6.15=he1e5248_0
  - greenlet=2.0.2=py39h227be39_0
  - grpc-cpp=1.46.1=h33aed49_0
  - grpcio=1.42.0=py39hce63b2e_0
  - gst-plugins-base=1.14.0=h8213a91_2
  - gstreamer=1.14.0=h28cd5cc_2
  - httplib2=0.18.1=pyh9f0ad1d_0
  - huggingface_hub=0.17.1=pyhd8ed1ab_0
  - icu=58.2=he6710b0_3
  - idna=3.4=py39h06a4308_0
  - importlib-metadata=4.11.3=py39h06a4308_0
  - importlib_metadata=4.11.3=hd3eb1b0_0
  - intel-openmp=2021.4.0=h06a4308_3561
  - ipykernel=6.15.2=py39h06a4308_0
  - ipython=8.6.0=py39h06a4308_0
  - ipython_genutils=0.2.0=pyhd3eb1b0_1
  - ipywidgets=7.6.5=pyhd3eb1b0_1
  - jedi=0.18.1=py39h06a4308_1
  - jinja2=3.1.2=py39h06a4308_0
  - joblib=1.1.1=py39h06a4308_0
  - jpeg=9e=h7f8727e_0
  - json5=0.9.6=pyhd3eb1b0_0
  - jsonschema=4.16.0=py39h06a4308_0
  - jupyter=1.0.0=py39h06a4308_8
  - jupyter_client=7.3.5=py39h06a4308_0
  - jupyter_console=6.4.3=pyhd3eb1b0_0
  - jupyter_core=4.11.2=py39h06a4308_0
  - jupyter_server=1.18.1=py39h06a4308_0
  - jupyterlab=3.4.4=py39h06a4308_0
  - jupyterlab_pygments=0.1.2=py_0
  - jupyterlab_server=2.15.2=py39h06a4308_0
  - jupyterlab_widgets=1.0.0=pyhd3eb1b0_1
  - kaggle=1.5.16=pyhd8ed1ab_0
  - kiwisolver=1.4.2=py39h295c915_0
  - krb5=1.19.2=hac12032_0
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=3.0=h295c915_0
  - libblas=3.9.0=12_linux64_mkl
  - libboost=1.73.0=h28710b8_12
  - libbrotlicommon=1.0.9=h166bdaf_7
  - libbrotlidec=1.0.9=h166bdaf_7
  - libbrotlienc=1.0.9=h166bdaf_7
  - libcblas=3.9.0=12_linux64_mkl
  - libclang=10.0.1=default_hb85057a_2
  - libcurl=7.85.0=h91b91d3_0
  - libdeflate=1.8=h7f8727e_5
  - libedit=3.1.20210910=h7f8727e_0
  - libev=4.33=h516909a_1
  - libevent=2.1.12=h8f2d780_0
  - libffi=3.3=he6710b0_2
  - libgcc-ng=12.2.0=h65d4601_19
  - libgfortran-ng=11.2.0=h00389a5_1
  - libgfortran5=11.2.0=h1234567_1
  - libiconv=1.16=h7f8727e_2
  - libidn2=2.3.2=h7f8727e_0
  - liblapack=3.9.0=12_linux64_mkl
  - libllvm10=10.0.1=hbcb73fb_5
  - libllvm11=11.1.0=h9e868ea_6
  - libnghttp2=1.46.0=hce63b2e_0
  - libpng=1.6.37=hbc83047_0
  - libpq=12.9=h16c4e8d_3
  - libprotobuf=3.20.1=h4ff587b_0
  - libsodium=1.0.18=h7b6447c_0
  - libssh2=1.10.0=ha56f1ee_2
  - libstdcxx-ng=12.2.0=h46fd767_19
  - libtasn1=4.16.0=h27cfd23_0
  - libthrift=0.15.0=hcc01f38_0
  - libtiff=4.4.0=hecacb30_2
  - libunistring=0.9.10=h27cfd23_0
  - libuuid=1.41.5=h5eee18b_0
  - libuv=1.40.0=h7b6447c_0
  - libwebp=1.2.4=h11a3e52_0
  - libwebp-base=1.2.4=h5eee18b_0
  - libxcb=1.15=h7f8727e_0
  - libxkbcommon=1.0.1=hfa300c1_0
  - libxml2=2.9.14=h74e7548_0
  - libxslt=1.1.35=h4e12654_0
  - llvm-openmp=14.0.6=h9e868ea_0
  - llvmlite=0.39.1=py39he621ea3_0
  - lxml=4.9.1=py39h1edc446_0
  - lz4-c=1.9.3=h295c915_1
  - markupsafe=2.1.1=py39h7f8727e_0
  - matplotlib=3.5.3=py39h06a4308_0
  - matplotlib-base=3.5.3=py39hf590b9c_0
  - matplotlib-inline=0.1.6=py39h06a4308_0
  - mistune=0.8.4=py39h27cfd23_1000
  - mkl=2021.4.0=h06a4308_640
  - mkl-service=2.4.0=py39h7f8727e_0
  - mkl_fft=1.3.1=py39hd3c417c_0
  - mkl_random=1.2.2=py39h51133e4_0
  - msgpack-python=1.0.5=py39h4b4f3f3_0
  - multidict=6.0.2=py39hb9d737c_1
  - multiprocess=0.70.13=py39hb9d737c_0
  - munkres=1.1.4=py_0
  - nbclassic=0.4.8=py39h06a4308_0
  - nbclient=0.5.13=py39h06a4308_0
  - nbconvert=6.5.4=py39h06a4308_0
  - nbformat=5.5.0=py39h06a4308_0
  - ncurses=6.4=hcb278e6_0
  - neovim=0.3.1=pyhd8ed1ab_3
  - nest-asyncio=1.5.5=py39h06a4308_0
  - nettle=3.7.3=hbbd107a_1
  - networkx=2.8.4=py39h06a4308_0
  - notebook=6.5.2=py39h06a4308_0
  - notebook-shim=0.2.2=py39h06a4308_0
  - nspr=4.33=h295c915_0
  - nss=3.74=h0370c37_0
  - numba=0.56.4=py39h61ddf18_0
  - numexpr=2.8.4=py39he184ba9_0
  - numpy=1.22.4=py39hc58783e_0
  - objsize=0.5.2=pyhd8ed1ab_0
  - openh264=2.1.1=h4ff587b_0
  - openssl=1.1.1w=hd590300_0
  - orc=1.7.4=h07ed6aa_0
  - orjson=3.8.2=py39hf5be78f_0
  - packaging=21.3=pyhd3eb1b0_0
  - pandas=1.5.1=py39h417a72b_0
  - pandocfilters=1.5.0=pyhd3eb1b0_0
  - parso=0.8.3=pyhd3eb1b0_0
  - pathtools=0.1.2=py_1
  - pcre=8.45=h295c915_0
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pillow=9.2.0=py39hace64e9_1
  - pip=22.2.2=py39h06a4308_0
  - ply=3.11=py39h06a4308_0
  - prometheus_client=0.14.1=py39h06a4308_0
  - promise=2.3=py39hf3d152e_7
  - prompt-toolkit=3.0.20=pyhd3eb1b0_0
  - prompt_toolkit=3.0.20=hd3eb1b0_0
  - proto-plus=1.22.1=pyhd8ed1ab_0
  - protobuf=3.20.1=py39h295c915_0
  - psutil=5.9.0=py39h5eee18b_0
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - pyarrow=8.0.0=py39h992f0b0_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pydot=1.2.4=py_0
  - pygments=2.11.2=pyhd3eb1b0_0
  - pykerberos=1.2.4=py39ha6ecad8_0
  - pymongo=3.13.0=py39h5a03fae_0
  - pynvim=0.4.3=pyhd8ed1ab_1
  - pyopenssl=22.0.0=pyhd3eb1b0_0
  - pyparsing=3.0.9=py39h06a4308_0
  - pyqt=5.15.7=py39h6a678d5_1
  - pyqt5-sip=12.11.0=py39h6a678d5_1
  - pyrsistent=0.18.0=py39heee7806_0
  - pysocks=1.7.1=py39h06a4308_0
  - python=3.9.7=h12debd9_1
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python-fastjsonschema=2.16.2=py39h06a4308_0
  - python-hdfs=2.7.0=pyhd8ed1ab_0
  - python-slugify=8.0.1=pyhd8ed1ab_0
  - python-xxhash=3.0.0=py39hb9d737c_1
  - python_abi=3.9=2_cp39
  - pytorch=1.12.1=py3.9_cuda11.3_cudnn8.3.2_0
  - pytorch-mutex=1.0=cuda
  - pytz=2022.1=py39h06a4308_0
  - pyyaml=6.0=py39hb9d737c_4
  - pyzmq=23.2.0=py39h6a678d5_0
  - qt-main=5.15.2=h327a75a_7
  - qt-webengine=5.15.9=hd2b0992_4
  - qtconsole=5.3.2=py39h06a4308_0
  - qtpy=2.2.0=py39h06a4308_0
  - qtwebkit=5.212=h4eab89a_4
  - re2=2022.04.01=h27087fc_0
  - readline=8.2=h5eee18b_0
  - regex=2022.7.9=py39h5eee18b_0
  - requests=2.28.1=py39h06a4308_0
  - requests-kerberos=0.12.0=py39hf3d152e_4
  - rhash=1.4.1=h3c74f83_1
  - sacremoses=0.0.43=pyhd3eb1b0_0
  - scikit-learn=1.1.3=py39h6a678d5_0
  - scipy=1.9.3=py39h14f4228_0
  - send2trash=1.8.0=pyhd3eb1b0_1
  - sentry-sdk=1.11.1=pyhd8ed1ab_0
  - setproctitle=1.3.2=py39hb9d737c_1
  - setuptools=65.5.0=py39h06a4308_0
  - shortuuid=1.0.11=pyhd8ed1ab_0
  - sip=6.6.2=py39h6a678d5_0
  - six=1.16.0=pyhd3eb1b0_1
  - smmap=5.0.0=pyhd8ed1ab_0
  - snappy=1.1.9=hbd366e4_1
  - sniffio=1.2.0=py39h06a4308_1
  - soupsieve=2.3.2.post1=py39h06a4308_0
  - sqlite=3.39.3=h5082296_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - tbb=2021.6.0=hdb19cb5_0
  - tensorboardx=2.5.1=pyhd8ed1ab_0
  - termcolor=2.1.0=pyhd8ed1ab_0
  - terminado=0.13.1=py39h06a4308_0
  - text-unidecode=1.3=py_0
  - threadpoolctl=2.2.0=pyh0d69192_0
  - timm=0.4.12=pyhd8ed1ab_0
  - tinycss2=1.2.1=py39h06a4308_0
  - tk=8.6.12=h1ccaba5_0
  - tokenizers=0.13.0.dev0=py39_0
  - toml=0.10.2=pyhd3eb1b0_0
  - torchaudio=0.12.1=py39_cu113
  - torchvision=0.13.1=py39_cu113
  - tornado=6.2=py39h5eee18b_0
  - tqdm=4.64.1=py39h06a4308_0
  - traitlets=5.1.1=pyhd3eb1b0_0
  - transformers=4.24.0=py_0
  - typing-extensions=4.3.0=py39h06a4308_0
  - typing_extensions=4.3.0=py39h06a4308_0
  - tzdata=2022f=h04d1e81_0
  - unidecode=1.3.6=pyhd8ed1ab_0
  - urllib3=1.26.12=py39h06a4308_0
  - utf8proc=2.6.1=h27cfd23_0
  - wandb=0.13.5=pyhd8ed1ab_0
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - webencodings=0.5.1=py39h06a4308_1
  - websocket-client=0.58.0=py39h06a4308_4
  - wheel=0.37.1=pyhd3eb1b0_0
  - widgetsnbextension=3.5.2=py39h06a4308_0
  - xxhash=0.8.0=h7f98852_3
  - xz=5.2.6=h5eee18b_0
  - yacs=0.1.8=pyhd8ed1ab_0
  - yaml=0.2.5=h7f98852_2
  - yarl=1.8.1=py39h5eee18b_0
  - zeromq=4.3.4=h2531618_0
  - zipp=3.8.0=py39h06a4308_0
  - zlib=1.2.13=h5eee18b_0
  - zsh=5.8=h3d38e88_1
  - zstandard=0.19.0=py39h29414ee_1
  - zstd=1.5.2=ha4553b6_0
  - pip:
    - antlr4-python3-runtime==4.8
    - apex==0.1
    - bitarray==2.6.0
    - cmake==3.25.0
    - colorama==0.4.6
    - fairseq==0.12.2
    - hydra-core==1.0.7
    - omegaconf==2.0.6
    - portalocker==2.6.0
    - sacrebleu==2.3.1
    - swin-window-process==0.0.0
    - tabulate==0.9.0
prefix: /gpfs/u/home/DLTM/DLTMhssn/scratch/py39_cu113
